name: Lint & Test PR

on:
  pull_request:
    branches: ['dev', 'master', 'next']

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: npm test
